/**
 * buildBrowser.js — bundle the Node decoder into a browser-usable IIFE so the
 * static PWA (docs/) and the Node server share ONE source of truth (no drift).
 * Output: docs/serial-decoder.browser.js exposing window.SerialDecoder.
 * Usage: node decoder/buildBrowser.js
 */
const fs = require('fs');
const path = require('path');
const dir = __dirname;

let brands = fs.readFileSync(path.join(dir, 'brands.js'), 'utf8');
let sd = fs.readFileSync(path.join(dir, 'serialDecoder.js'), 'utf8');

// Strip Node module wiring so the two files can share one scope.
brands = brands.replace(/module\.exports\s*=\s*\{[^{}]*\};\s*$/m, '');
sd = sd.replace(/const\s*\{[^}]*\}\s*=\s*require\('\.\/brands'\);\s*/, '');
sd = sd.replace(/module\.exports\s*=\s*\{[^{}]*\};\s*$/m, '');

const out = `/* AUTO-GENERATED by decoder/buildBrowser.js from brands.js + serialDecoder.js. DO NOT EDIT. */
;(function (global) {
'use strict';
${brands}
${sd}
  global.SerialDecoder = { decode: decode, findBrand: findBrand, BRANDS: BRANDS, METHODS: METHODS };
})(typeof window !== 'undefined' ? window : this);
`;

const target = path.join(dir, '..', 'docs', 'serial-decoder.browser.js');
fs.writeFileSync(target, out);
console.log(`wrote ${path.relative(path.join(dir, '..'), target)} (${out.length} bytes)`);
